//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyProduct("Microsoft Dynamics® CRM")]
[assembly: System.Reflection.AssemblyCopyright("© 2015 Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyTitle("CommonTypes")]
[assembly: System.Reflection.AssemblyVersion("8.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("8.2.0.556")]

// Generated by the MSBuild WriteCodeFragment class on 10/23/2016 10:08:13 AM.

